/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.karam.dentistry.customer;

import com.karam.dentistry.Main;
import com.karam.dentistry.data.Patient;
import com.karam.dentistry.utilities.ImageUtils;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author karam
 */
public class AddCustomer extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    
    private UUID UID;
    
    public AddCustomer() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        UID = UUID.randomUUID();
        uidTextField.setText(UID.toString());
        
        // resize image
        Image image = ((ImageIcon) profilePicture.getIcon()).getImage();
        profilePicture.setIcon(ImageUtils.scaleImage(image, 72, 72));    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profilePicture = new javax.swing.JLabel();
        uidTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        registerPatientButton = new javax.swing.JButton();
        firstNameSelector = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastNameSelector = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dobSelector = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        genderSelectorr = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        occupationSelector = new javax.swing.JTextField();
        nationalitySelector = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phoneNumberSelector = new javax.swing.JTextField();
        emailSelector = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        citizenshipSelector = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        provinceSelector = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        postalCodeSelectorr = new javax.swing.JTextField();
        citySelector = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addressSelector = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        uploadPictureButton = new javax.swing.JButton();
        streetNumberSelectorr = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        removePictureButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        insuranceCompanySelector = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        insuranceNumberSelector = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        insuranceEmployerSelector = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        insuranceTelephoneSelector = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        profilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/karam/dentistry/images/smile.png"))); // NOI18N
        jPanel1.add(profilePicture);
        profilePicture.setBounds(6, 6, 72, 72);

        uidTextField.setEditable(false);
        uidTextField.setText("jTextField1");
        jPanel1.add(uidTextField);
        uidTextField.setBounds(41, 112, 260, 22);

        jLabel1.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel1.setText("UID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 110, 23, 33);

        registerPatientButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerPatientButton.setText("REGISTER PATIENT");
        registerPatientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerPatientButtonMousePressed(evt);
            }
        });
        jPanel1.add(registerPatientButton);
        registerPatientButton.setBounds(430, 13, 220, 80);

        firstNameSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(firstNameSelector);
        firstNameSelector.setBounds(100, 170, 210, 20);

        jLabel2.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 170, 70, 20);

        lastNameSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(lastNameSelector);
        lastNameSelector.setBounds(101, 200, 210, 20);

        jLabel3.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 200, 63, 20);
        jPanel1.add(dobSelector);
        dobSelector.setBounds(100, 230, 210, 22);

        jLabel4.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 260, 50, 20);

        jLabel5.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel5.setText("Date of Birth");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 230, 75, 22);

        genderSelectorr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Not Specified" }));
        jPanel1.add(genderSelectorr);
        genderSelectorr.setBounds(100, 260, 207, 22);

        jLabel8.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel8.setText("Occupation");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 170, 70, 20);

        occupationSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(occupationSelector);
        occupationSelector.setBounds(420, 170, 230, 22);

        nationalitySelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(nationalitySelector);
        nationalitySelector.setBounds(420, 200, 230, 20);

        jLabel9.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel9.setText("Nationality");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 200, 70, 20);

        jLabel10.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel10.setText("Phone Number");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 410, 90, 20);

        phoneNumberSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(phoneNumberSelector);
        phoneNumberSelector.setBounds(420, 410, 230, 20);

        emailSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(emailSelector);
        emailSelector.setBounds(420, 230, 230, 20);

        jLabel11.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel11.setText("Email");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(380, 230, 40, 20);

        jLabel12.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel12.setText("PERSONAL INFORMATION");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 140, 300, 30);

        jLabel13.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel13.setText("Citizenship");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(350, 260, 70, 20);

        citizenshipSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(citizenshipSelector);
        citizenshipSelector.setBounds(420, 260, 230, 20);

        jLabel14.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel14.setText("Province");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(50, 410, 60, 20);

        provinceSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(provinceSelector);
        provinceSelector.setBounds(110, 410, 200, 20);

        jLabel15.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel15.setText("Postal Code");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(330, 380, 70, 20);

        postalCodeSelectorr.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(postalCodeSelectorr);
        postalCodeSelectorr.setBounds(410, 380, 240, 20);

        citySelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(citySelector);
        citySelector.setBounds(410, 350, 240, 20);

        jLabel17.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel17.setText("City");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(380, 350, 30, 20);

        jLabel18.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel18.setText("Street Number");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 380, 90, 20);

        addressSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(addressSelector);
        addressSelector.setBounds(110, 350, 200, 20);

        jLabel19.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel19.setText("ADDRESS");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 320, 300, 30);

        uploadPictureButton.setText("UPLOAD PICTURE");
        uploadPictureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadPictureButtonMouseClicked(evt);
            }
        });
        jPanel1.add(uploadPictureButton);
        uploadPictureButton.setBounds(6, 79, 135, 23);

        streetNumberSelectorr.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jPanel1.add(streetNumberSelectorr);
        streetNumberSelectorr.setBounds(110, 380, 200, 20);

        jLabel23.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel23.setText("Address");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(60, 350, 49, 20);

        removePictureButton.setText("REMOVE PICTURE");
        removePictureButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removePictureButtonMouseClicked(evt);
            }
        });
        jPanel1.add(removePictureButton);
        removePictureButton.setBounds(147, 79, 150, 23);

        jLabel6.setFont(new java.awt.Font("Sans Serif Collection", 1, 14)); // NOI18N
        jLabel6.setText("INSURANCE");

        jLabel16.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel16.setText("Company Name");

        insuranceCompanySelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel20.setText("ID NUMBER");

        insuranceNumberSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel21.setText("Company Telephone");

        insuranceEmployerSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Sans Serif Collection", 1, 12)); // NOI18N
        jLabel22.setText("Employer");

        insuranceTelephoneSelector.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insuranceNumberSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(12, 12, 12)
                                .addComponent(insuranceCompanySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insuranceEmployerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(insuranceTelephoneSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceCompanySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceEmployerSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceNumberSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceTelephoneSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerPatientButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerPatientButtonMousePressed
        // TODO add your handling code here:
        
        if (dobSelector.getDate() == null){
            JOptionPane.showMessageDialog(this, "You cannot have an empty date of birth!", "Error!", JOptionPane.OK_OPTION);
            return;
        }
        
        SimpleDateFormat sdf = new SimpleDateFormat("MMM dd, yyyy");
        
        Patient patient = new Patient(UID);
        
        patient.setFirstName(this.firstNameSelector.getText());
        patient.setLastName(this.lastNameSelector.getText());
        patient.setDob(sdf.format(this.dobSelector.getDate()));
        patient.setGender(this.genderSelectorr.getSelectedItem().toString());
        patient.setNationality(this.nationalitySelector.getText());
        patient.setCitizenship(this.citizenshipSelector.getText());
        patient.setEmail(this.emailSelector.getText());
                
        Image image = ((ImageIcon) profilePicture.getIcon()).getImage();
        patient.setProfilePicture(image);
        
        // addrress
        patient.setAddress(this.addressSelector.getText());
        patient.setCity(this.citySelector.getText());
        patient.setStreetNumber(this.streetNumberSelectorr.getText());
        patient.setProvince(this.provinceSelector.getText());
        patient.setPostalCode(this.postalCodeSelectorr.getText());
        patient.setPhoneNumber(this.phoneNumberSelector.getText());
        
        // insurrnace
        patient.setCompanyName(this.insuranceCompanySelector.getText());
        patient.setEmployer(this.insuranceEmployerSelector.getText());
        patient.setIdNumber(this.insuranceNumberSelector.getText());
        patient.setCompanyTelephone(this.insuranceTelephoneSelector.getText());
        
        Main.getInstance().getDataManager().addPatientToDatabase(patient);
        Main.getInstance().getCustomer().refreshTable();
        
        this.dispose();
    }//GEN-LAST:event_registerPatientButtonMousePressed

    private void uploadPictureButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadPictureButtonMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select profile picture image");

        // add a filter to allow only PNG and JPG files
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files (*.png, *.jpg, *jpeg)", "png", "jpg", "jpeg");
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setMultiSelectionEnabled(false);

        // shows the menu and waits for user input
        int result = fileChooser.showOpenDialog(this);

        // Check if the user selected file is an image
        if (result == JFileChooser.APPROVE_OPTION) {
            File chosenFile = fileChooser.getSelectedFile();
            try {
                Image image = ImageIO.read(chosenFile);
                profilePicture.setIcon(ImageUtils.scaleImage(image, 72, 72));
                JOptionPane.showMessageDialog(this, "Successfully set the profile picture to " + chosenFile.getName(), "Success!", JOptionPane.OK_OPTION);
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed to set the profile picture to " + chosenFile.getName(), "Error!", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_uploadPictureButtonMouseClicked

    private void removePictureButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removePictureButtonMouseClicked
        try {
            Image image = (Image) ImageIO.read(getClass().getResource("/com/karam/dentistry/images/smile.png"));
            profilePicture.setIcon(ImageUtils.scaleImage(image, 72, 72));
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to set the profile picture to the default image.", "Error!", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_removePictureButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressSelector;
    private javax.swing.JTextField citizenshipSelector;
    private javax.swing.JTextField citySelector;
    private com.toedter.calendar.JDateChooser dobSelector;
    private javax.swing.JTextField emailSelector;
    private javax.swing.JTextField firstNameSelector;
    private javax.swing.JComboBox<String> genderSelectorr;
    private javax.swing.JTextField insuranceCompanySelector;
    private javax.swing.JTextField insuranceEmployerSelector;
    private javax.swing.JTextField insuranceNumberSelector;
    private javax.swing.JTextField insuranceTelephoneSelector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameSelector;
    private javax.swing.JTextField nationalitySelector;
    private javax.swing.JTextField occupationSelector;
    private javax.swing.JTextField phoneNumberSelector;
    private javax.swing.JTextField postalCodeSelectorr;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JTextField provinceSelector;
    private javax.swing.JButton registerPatientButton;
    private javax.swing.JButton removePictureButton;
    private javax.swing.JTextField streetNumberSelectorr;
    private javax.swing.JTextField uidTextField;
    private javax.swing.JButton uploadPictureButton;
    // End of variables declaration//GEN-END:variables
}
